/**
 * @copyright SPDX-License-Identifier: Apache-2.0
 * @file mini_config.h
 * @brief mini-os configuration heaper - only include definitions
 * @author H-000-H
 * @details every option in this file resolves through the same three-tier chain,
 *          so it can come from the kconfig system, from an outside build system,
 *          or fall back to the in-tree default:
 *  - 1. CONFIG_<NAME>      : generated by mini-tree's kconfig system (config.h)
 *  - 2. MINI_OS_<NAME>     : pre-defined from the outside (-D... on the command
 *                            line or by a parent project); kept as it is
 *  - 3. built-in default   : the value mini-os ships with
 * @note a feature switch is always DEFINED, either 1 or 0, so it must be tested
 *       with #if, never with #ifdef: #ifdef is true for a disabled option too
 */
#ifndef MINI_CONFIG_H
#define MINI_CONFIG_H

/**
 * @details
 * - Include <config.h> and <compiler_compat.h> if they exist that identify using mini-tree's
 * kconfig system
 * - couldn't include <compiler_compat.h> .if included, compiler_compat.h it has conflicts
 */
#if __has_include(<config.h>) && __has_include(<compiler_compat.h>)
#include <config.h>
#endif

/**
 * @brief Define MINI_OS_NULL_TO_STANDARD to use standard NULL macro instead of 0
 * @note on by default; set CONFIG_MINI_OS_NULL_TO_STANDARD=0 for a plain 0 NULL
 */
#ifdef CONFIG_MINI_OS_NULL_TO_STANDARD
#define MINI_OS_NULL_TO_STANDARD CONFIG_MINI_OS_NULL_TO_STANDARD
#elif defined(MINI_OS_NULL_TO_STANDARD)
/* MINI_OS_NULL_TO_STANDARD pre-defined externally , keep it */
#else
#define MINI_OS_NULL_TO_STANDARD 1
#endif

/**
 * @brief Define CONFIG_THREADS_NAME_MAX to set the maximum length of thread names
 */
#ifdef CONFIG_THREADS_NAME_LEN
#define MINI_OS_THREADS_NAME_LEN CONFIG_THREADS_NAME_LEN /**< max thread name length (incl. NUL) */
#elif defined(MINI_OS_THREADS_NAME_LEN)
/* MINI_OS_THREADS_NAME_LEN pre-defined externally , keep it */
#else
#define MINI_OS_THREADS_NAME_LEN 32 /**< max thread name length (incl. NUL) */
#endif

#ifdef CONFIG_QUEUE_NAME_LEN
#define MINI_OS_QUEUE_NAME_LEN CONFIG_QUEUE_NAME_LEN /**< max queue name length (incl. NUL) */
#elif defined(MINI_OS_QUEUE_NAME_LEN)
/* MINI_OS_QUEUE_NAME_LEN pre-defined externally , keep it */
#else
#define MINI_OS_QUEUE_NAME_LEN 32 /**< max queue name length (incl. NUL) */
#endif

#ifdef CONFIG_SEMAPHORE_NAME_LEN
#define MINI_OS_SEMAPHORE_NAME_LEN CONFIG_SEMAPHORE_NAME_LEN /**< max semaphore name length (incl. NUL) */
#elif defined(MINI_OS_SEMAPHORE_NAME_LEN)
/* MINI_OS_SEMAPHORE_NAME_LEN pre-defined externally , keep it */
#else
#define MINI_OS_SEMAPHORE_NAME_LEN 32 /**< max semaphore name length (incl. NUL) */
#endif

#define MINI_OS_IDLE_THREAD_NAME "idle_thread" /**< idle thread name */

#define MINI_OS_IDLE_THREAD_CONSTRUCTOR 105        /**< idle thread constructor priority */
#define MINI_OS_FIND_BY_NAME_CONSTRUCTOR 110       /**< find by name constructor priority */
#define MINI_OS_SEMAPHORE_REGISTRY_CONSTRUCTOR 111 /**< semaphore by-name registry constructor priority */
#define MINI_OS_MUTEX_REGISTRY_CONSTRUCTOR 112     /**< mutex by-name registry constructor priority */
#define MINI_OS_FPU_ENABLE_CONSTRUCTOR 100         /**< FPU enable constructor priority (0-100 reserved; runs first) */
#define MINI_OS_CPU_PROBE_CONSTRUCTOR 101          /**< CPUID probe constructor priority (fails fast before any thread runs) */
#define MINI_OS_STACK_SENTINEL_CONSTRUCTOR 102     /**< stack sentinel constructor priority (after CPU probe, before threads) */
#define MINI_OS_TIMER_DESTRUCTOR 113               /**< timer module self-init constructor priority */

/**
 * @brief Soft-timer service thread name / priority / stack size
 * @note the service thread runs the SOFT timer callbacks in thread context; it
 *       sits one priority step ABOVE the idle thread: sharing the lowest level
 *       with the reaper meant any code that locates a thread by priority could
 *       land in the endless idle loop instead of the service thread. It still
 *       never preempts application work and is spawned lazily on the first SOFT
 *       timer start (the scheduler must be up, which happens in main after the
 *       constructors, so it cannot be created from the constructor itself).
 *       MINI_OS_TIMER_THREAD_STACK_SIZE must be >= MINI_OS_THREAD_MIN_STACK_SIZE
 *       and a multiple of 8.
 */
#define MINI_OS_TIMER_THREAD_NAME "timer_thread"             /**< soft-timer service thread name */
#define MINI_OS_TIMER_THREAD_PRIORITY (MINI_OS_PRIORITY - 2) /**< one step above idle: never shares the lowest level */
#ifdef CONFIG_MINI_OS_TIMER_THREAD_STACK_SIZE
#define MINI_OS_TIMER_THREAD_STACK_SIZE CONFIG_MINI_OS_TIMER_THREAD_STACK_SIZE /**< service thread stack bytes */
#elif defined(MINI_OS_TIMER_THREAD_STACK_SIZE)
/* MINI_OS_TIMER_THREAD_STACK_SIZE pre-defined externally , keep it */
#else
#define MINI_OS_TIMER_THREAD_STACK_SIZE 512 /**< service thread stack bytes */
#endif
/**
 * @brief Enable stack overflow detection on the system (MSP) stack
 * @note Off by default; set CONFIG_MINI_OS_STACK_OVERFLOW_CHECK=1 to enable.
 *       Plants a magic word at the stack's low boundary (linker symbol
 *       __mini_os_heap_end from mini-os-heap.ld, where heap ends and the
 *       system stack begins); the idle thread re-checks it every loop and
 *       halts when the stack ran over the boundary into the heap.
 */
#ifdef CONFIG_MINI_OS_STACK_OVERFLOW_CHECK
#define MINI_OS_STACK_OVERFLOW_CHECK CONFIG_MINI_OS_STACK_OVERFLOW_CHECK
#elif defined(MINI_OS_STACK_OVERFLOW_CHECK)
/* MINI_OS_STACK_OVERFLOW_CHECK pre-defined externally , keep it */
#else
#define MINI_OS_STACK_OVERFLOW_CHECK 0
#endif

#define MINI_OS_STACK_MAGIC 0x060815U /**< stack/ overflow sentinel word */

#ifdef CONFIG_MINI_EXECUTION_SLAB_CHECK_SIZE
#define MINI_OS_SLAB_CHECK_SIZE CONFIG_MINI_EXECUTION_SLAB_CHECK_SIZE /**< slab check size for execution (0 = disabled) */
#elif defined(MINI_OS_SLAB_CHECK_SIZE)
/* MINI_OS_SLAB_CHECK_SIZE pre-defined externally , keep it */
#else
#define MINI_OS_SLAB_CHECK_SIZE 0 /**< slab check size for execution (0 = disabled) */
#endif

#ifdef CONFIG_MINI_OS_PRIORITY
#define MINI_OS_PRIORITY CONFIG_MINI_OS_PRIORITY /**< number of priorities (smaller number = higher priority) */
#elif defined(MINI_OS_PRIORITY)
/* MINI_OS_PRIORITY pre-defined externally , keep it */
#else
#define MINI_OS_PRIORITY 32 /**< number of priorities (smaller number = higher priority) */
#endif

#ifdef CONFIG_MINI_OS_THREAD_MIN_STACK_SIZE
#define MINI_OS_THREAD_MIN_STACK_SIZE CONFIG_MINI_OS_THREAD_MIN_STACK_SIZE /**< minimum stack size enforced at thread create */
#elif defined(MINI_OS_THREAD_MIN_STACK_SIZE)
/* MINI_OS_THREAD_MIN_STACK_SIZE pre-defined externally , keep it */
#else
#define MINI_OS_THREAD_MIN_STACK_SIZE 256 /**< minimum stack size enforced at thread create */
#endif
/**
 * @brief Enable thread detach/join support (adds the per-thread corpse fields)
 * @note Off by default; set CONFIG_MINI_OS_THREAD_DETACH=1 in config.h to enable.
 *       The switch covers mini_os_thread_detach() AND mini_os_thread_join()
 *       together on purpose: they are two halves of the same corpse-lifetime
 *       mechanism and neither works standalone.
 *  - a join pins the corpse (is_detach = MINI_OS_FALSE) so the idle reaper
 *    cannot free the TCB while the return value is still needed, and unpins it
 *    again on success (or restores the previous detach state on timeout)
 *  - detach is only meaningful because a join can pin the corpse in the first
 *    place; without join, is_detach is permanently true and the idle reaper
 *    collects every thread the moment it terminates
 * @note enabling it adds is_detach / is_terminated / exit_retval /
 *       join_wait_sem to every TCB
 */
#ifdef CONFIG_MINI_OS_THREAD_DETACH
#define MINI_OS_THREAD_DETACH CONFIG_MINI_OS_THREAD_DETACH
#elif defined(MINI_OS_THREAD_DETACH)
/* MINI_OS_THREAD_DETACH pre-defined externally , keep it */
#else
#define MINI_OS_THREAD_DETACH 0
#endif

/* Number of 32-bit ready-group words (32 priorities per word) */
#ifdef CONFIG_MINI_OS_PRIORITY
#define MINI_OS_PRIORITY_NUM (CONFIG_MINI_OS_PRIORITY / 32) /**< number of 32-bit ready-group words */
#elif defined(MINI_OS_PRIORITY_NUM)
/* MINI_OS_PRIORITY_NUM pre-defined externally , keep it */
#else
#define MINI_OS_PRIORITY_NUM (MINI_OS_PRIORITY / 32) /**< number of 32-bit ready-group words */
#endif

/* Sub-groups per priority (time-slice granularity within one priority) */
#ifdef CONFIG_MINI_OS_SAME_PRIORITY
#define MINI_OS_SAME_PRIORITY CONFIG_MINI_OS_SAME_PRIORITY /**< sub-groups per priority (time-slice granularity) */
#elif defined(MINI_OS_SAME_PRIORITY)
/* MINI_OS_SAME_PRIORITY pre-defined externally , keep it */
#else
#define MINI_OS_SAME_PRIORITY (MINI_OS_PRIORITY / 8) /**< sub-groups per priority (time-slice granularity) */
#endif

/* Architecture selector. Numeric so it can be used in preprocessor #if
 * comparisons (e.g. port.S selects per-core constants). */
#define MINI_OS_ARCH_M0 0 /**< Cortex-M0 architecture id */
#define MINI_OS_ARCH_M3 1 /**< Cortex-M3 architecture id */
#define MINI_OS_ARCH_M4 2 /**< Cortex-M4 architecture id */
#define MINI_OS_ARCH_M7 3 /**< Cortex-M7 architecture id */

#ifdef CONFIG_ARCH
#define MINI_OS_ARCH CONFIG_ARCH /**< selected architecture id */
#elif defined(MINI_OS_ARCH)
/* MINI_OS_ARCH pre-defined externally , keep it */
#else
#define MINI_OS_ARCH MINI_OS_ARCH_M4 /**< default architecture id (Cortex-M4) */
#endif

/* Per-architecture constants derived from MINI_OS_ARCH (used by port.S) */
#if MINI_OS_ARCH == MINI_OS_ARCH_M0
#define MINI_OS_NVIC_PRIO_BITS 2 /**< Cortex-M0/M0+: 2 NVIC priority bits */
#define MINI_OS_ARCH_HAS_FPU 0   /**< Cortex-M0/M0+: no FPU */
#elif MINI_OS_ARCH == MINI_OS_ARCH_M3
#define MINI_OS_NVIC_PRIO_BITS 4 /**< Cortex-M3: 4 NVIC priority bits */
#define MINI_OS_ARCH_HAS_FPU 0   /**< Cortex-M3: no FPU */
#elif MINI_OS_ARCH == MINI_OS_ARCH_M4
#define MINI_OS_NVIC_PRIO_BITS 4 /**< Cortex-M4: 4 NVIC priority bits */
#define MINI_OS_ARCH_HAS_FPU 1   /**< Cortex-M4: optional single-precision FPU */
#elif MINI_OS_ARCH == MINI_OS_ARCH_M7
#define MINI_OS_NVIC_PRIO_BITS 4          /**< Cortex-M7: 4 NVIC priority bits */
#define MINI_OS_ARCH_HAS_FPU 1            /**< Cortex-M7: optional single/double-precision FPU */
/* L1 cache maintenance flags for mini_os_dcache_ops (bitmask) */
#define MINI_OS_CACHE_FLUSH (1 << 0)      /**< clean: write dirty lines back to memory */
#define MINI_OS_CACHE_INVALIDATE (1 << 1) /**< invalidate: drop the cached copies */
#define MINI_OS_CACHE_LINESIZE 32U        /**< Cortex-M7 L1 cache line size in bytes */
#else
#error "unsupported MINI_OS_ARCH value"
#endif

/* Critical-section interrupt masking policy. By default the critical section
 * API masks ALL interrupts via PRIMASK. Defining MINI_OS_IRQ_MAX_SYSCALL_PRIORITY
 * switches M3/M4/M7 critical sections to BASEPRI: only interrupts whose NVIC
 * priority number is >= this value are masked, more urgent ones (numerically
 * lower) can still preempt the kernel (FreeRTOS configMAX_SYSCALL_INTERRUPT_PRIORITY
 * style). Cortex-M0 has no BASEPRI hardware and always uses PRIMASK. */
#ifdef CONFIG_MINI_OS_IRQ_MAX_SYSCALL_PRIORITY
#define MINI_OS_IRQ_MAX_SYSCALL_PRIORITY CONFIG_MINI_OS_IRQ_MAX_SYSCALL_PRIORITY /**< BASEPRI threshold (NVIC priority number) */
#elif defined(MINI_OS_IRQ_MAX_SYSCALL_PRIORITY)
/* MINI_OS_IRQ_MAX_SYSCALL_PRIORITY pre-defined externally , keep it */
#else
/* not defined by default: critical sections mask all interrupts via PRIMASK */
#endif

#if defined(MINI_OS_IRQ_MAX_SYSCALL_PRIORITY)
#if MINI_OS_ARCH == MINI_OS_ARCH_M0
#error "MINI_OS_IRQ_MAX_SYSCALL_PRIORITY: Cortex-M0 has no BASEPRI hardware, remove it"
#endif
#if MINI_OS_IRQ_MAX_SYSCALL_PRIORITY == 0
#error "MINI_OS_IRQ_MAX_SYSCALL_PRIORITY must be non-zero (0 would mask nothing)"
#endif
#if MINI_OS_IRQ_MAX_SYSCALL_PRIORITY >= (1 << MINI_OS_NVIC_PRIO_BITS)
#error "MINI_OS_IRQ_MAX_SYSCALL_PRIORITY exceeds the NVIC priority range"
#endif
#define MINI_OS_IRQ_USE_BASEPRI 1 /**< critical sections mask via BASEPRI threshold */

/* BASEPRI stores the threshold in the upper MINI_OS_NVIC_PRIO_BITS bits of its
 * byte-wide register field, shift the priority number into register position.
 * Used by both redef.h callers and the port.S implementation. */
#define MINI_OS_IRQ_BASEPRI_THRESHOLD ((MINI_OS_IRQ_MAX_SYSCALL_PRIORITY) << (8U - MINI_OS_NVIC_PRIO_BITS)) /**< BASEPRI register value for the threshold */
#else
#define MINI_OS_IRQ_USE_BASEPRI 0 /**< critical sections mask everything via PRIMASK */
#endif

/**
 * @brief Enable FPU context save/restore in the PendSV switch (M4/M7 only)
 * @note Off by default; set CONFIG_MINI_OS_USE_FPU=1 in config.h to enable.
 *       Adds one flag word to every thread's initial stack frame and saves
 *       s16-s31 on switch when the thread used the FPU.
 */

#define MINI_OS_NO_FPU 0
#define MINI_OS_FPU 1
#ifdef CONFIG_MINI_OS_USE_FPU
#define MINI_OS_USE_FPU CONFIG_MINI_OS_USE_FPU
#elif defined(MINI_OS_USE_FPU)
/* MINI_OS_USE_FPU pre-defined externally , keep it */
#else
#define MINI_OS_USE_FPU MINI_OS_NO_FPU
#endif

/* Default idle stack size for threads. Must stay >= MINI_OS_THREAD_MIN_STACK_SIZE,
 * otherwise the idle thread creation is rejected by the stack size check */
#ifdef CONFIG_MINI_OS_DEFAULT_IDLE_STACK_SIZE
#define MINI_OS_DEFAULT_IDLE_STACK_SIZE CONFIG_MINI_OS_DEFAULT_IDLE_STACK_SIZE /**< default idle stack size in bytes */
#elif defined(MINI_OS_DEFAULT_IDLE_STACK_SIZE)
/* MINI_OS_DEFAULT_IDLE_STACK_SIZE pre-defined externally , keep it */
#else
#define MINI_OS_DEFAULT_IDLE_STACK_SIZE 256 /**< default idle stack size in bytes */
#endif

#define MINI_OS_CONTROL_REGISTER_MSP_PRIVILEGE 0U /**< CONTROL: MSP, privileged thread mode */
#define MINI_OS_CONTROL_REGISTER_MSP_USER 1U      /**< CONTROL: MSP, unprivileged thread mode */
#define MINI_OS_CONTROL_REGISTER_PSP_PRIVILEGE 2U /**< CONTROL: PSP, privileged thread mode */
#define MINI_OS_CONTROL_REGISTER_PSP_USER 3U      /**< CONTROL: PSP, unprivileged thread mode */
#define MINI_OS_NONE_THREAD_TO_RESTORE 0U         /**< marker: no thread to restore on first switch */

#ifdef CONFIG_MINI_OS_TICK_WHEEL
#define MINI_OS_TICK_WHEEL CONFIG_MINI_OS_TICK_WHEEL /**< tick wheel size (power of 2, number of slots) */
#elif defined(MINI_OS_TICK_WHEEL)
/* MINI_OS_TICK_WHEEL pre-defined externally , keep it */
#else
#define MINI_OS_TICK_WHEEL 32U /**< tick wheel size (power of 2, number of slots) */
#endif

#define MINI_OS_TICK_WHEEL_MASK (MINI_OS_TICK_WHEEL - 1) /**< tick wheel slot mask */

/**
 * @brief Enable 64-bit long tick counting (adds a 32-bit wrap-around counter)
 * @note Off by default; set CONFIG_MINI_OS_LONG_TIME=1 in config.h to enable.
 *       Without it the tick counter is the plain 32-bit g_global_tick and
 *       mini_os_get_tick_long_time() is not compiled.
 */
#ifdef CONFIG_MINI_OS_LONG_TIME
#define MINI_OS_LONG_TIME CONFIG_MINI_OS_LONG_TIME /**< enable 64-bit long tick counting (overflow counter) */
#elif defined(MINI_OS_LONG_TIME)
/* MINI_OS_LONG_TIME pre-defined externally , keep it */
#else
#define MINI_OS_LONG_TIME 0 /**< 0 = 32-bit tick counter only */
#endif

/**
 * @brief OS tick rate in Hz (default 1000 = one tick per millisecond)
 * @note value is the tick frequency, not a period; used by the tick/ms conversion macros
 */
#ifdef CONFIG_MINI_OS_DEFAULT_SYSTICK
#define MINI_OS_DEFAULT_SYSTICK CONFIG_MINI_OS_DEFAULT_SYSTICK /**< OS tick rate in Hz */
#elif defined(MINI_OS_DEFAULT_SYSTICK)
/* MINI_OS_DEFAULT_SYSTICK pre-defined externally , keep it */
#else
#define MINI_OS_DEFAULT_SYSTICK 1000U /**< OS tick rate in Hz */
#endif

/**
 * @brief CPU clock frequency in Hz, used to derive the SysTick reload value
 * @note reload = (MINI_OS_CPU_CLOCK_HZ / 1000) * ticks_per_ms - 1
 */
#ifdef CONFIG_MINI_OS_CPU_CLOCK_HZ
#define MINI_OS_CPU_CLOCK_HZ CONFIG_MINI_OS_CPU_CLOCK_HZ /**< CPU clock in Hz */
#elif defined(MINI_OS_CPU_CLOCK_HZ)
/* MINI_OS_CPU_CLOCK_HZ pre-defined externally , keep it */
#else
#define MINI_OS_CPU_CLOCK_HZ 72000000U /**< CPU clock in Hz */
#endif

/**
 * @brief open time slice configuration
 */
#ifdef CONFIG_MINI_OS_TIME_SLICE
#define MINI_OS_TIME_SLICE CONFIG_MINI_OS_TIME_SLICE
#elif defined(MINI_OS_TIME_SLICE)
/* MINI_OS_TIME_SLICE pre-defined externally , keep it */
#else
#define MINI_OS_TIME_SLICE 0
#endif

/**
 * @brief enable thread find by name
 */
#ifdef CONFIG_MINI_OS_FIND_BY_NAME
#define MINI_OS_FIND_BY_NAME CONFIG_MINI_OS_FIND_BY_NAME
#elif defined(MINI_OS_FIND_BY_NAME)
/* MINI_OS_FIND_BY_NAME pre-defined externally , keep it */
#else
#define MINI_OS_FIND_BY_NAME 0
#endif

/**
 * @brief enable event group support
 */
#ifdef CONFIG_MINI_OS_EVENT
#define MINI_OS_EVENT CONFIG_MINI_OS_EVENT
#elif defined(MINI_OS_EVENT)
/* MINI_OS_EVENT pre-defined externally , keep it */
#else
#define MINI_OS_EVENT 0
#endif

/**
 * @brief Maximum number of links walked when a mutex priority inheritance
 *        requirement is pushed along a chain of blocked owners
 * @note a chain longer than this stops being propagated; the cap also breaks
 *       out of a wait cycle (A waits B, B waits A) instead of looping forever
 */
#ifdef CONFIG_MINI_OS_MUTEX_PI_CHAIN_MAX
#define MINI_OS_MUTEX_PI_CHAIN_MAX CONFIG_MINI_OS_MUTEX_PI_CHAIN_MAX /**< inheritance chain depth cap */
#elif defined(MINI_OS_MUTEX_PI_CHAIN_MAX)
/* MINI_OS_MUTEX_PI_CHAIN_MAX pre-defined externally , keep it */
#else
#define MINI_OS_MUTEX_PI_CHAIN_MAX 8u /**< inheritance chain depth cap */
#endif

/**
 * @brief enable spinlock support (disabled by default; off kernels compile
 *        inc/spinlock.h to nothing)
 */
#ifdef CONFIG_MINI_OS_SPINLOCK
#define MINI_OS_SPINLOCK CONFIG_MINI_OS_SPINLOCK
#elif defined(MINI_OS_SPINLOCK)
/* MINI_OS_SPINLOCK pre-defined externally , keep it */
#else
#define MINI_OS_SPINLOCK 0
#endif

#ifdef CONFIG_MINI_OS_SPINLOCK_ATOMIC
#define MINI_OS_SPINLOCK_ATOMIC CONFIG_MINI_OS_SPINLOCK_ATOMIC
#elif defined(MINI_OS_SPINLOCK_ATOMIC)
/* MINI_OS_SPINLOCK_ATOMIC pre-defined externally , keep it */
#else
#define MINI_OS_SPINLOCK_ATOMIC 0
#endif

#ifdef CONFIG_MINI_OS_SPINLOCK_NUM
#define MINI_OS_SPINLOCK_NUM CONFIG_MINI_OS_SPINLOCK_NUM
#elif defined(MINI_OS_SPINLOCK_NUM)
/* MINI_OS_SPINLOCK_NUM pre-defined externally , keep it */
#else
#define MINI_OS_SPINLOCK_NUM 256
#endif

/**
 * @brief enable the bounded spin loop (pause + released-polling) between
 *        schedule_yield retries in the atomic-mode spinlock
 * @note disabled by default: each retry is a pure delay (one pause) plus a
 *       schedule_yield; only pay the polling loop when explicitly enabled.
 *       MINI_OS_SPINLOCK_NUM is only used when this is on.
 */
#ifdef CONFIG_MINI_OS_SPINLOCK_YIELD
#define MINI_OS_SPINLOCK_YIELD CONFIG_MINI_OS_SPINLOCK_YIELD
#elif defined(MINI_OS_SPINLOCK_YIELD)
/* MINI_OS_SPINLOCK_YIELD pre-defined externally , keep it */
#else
#define MINI_OS_SPINLOCK_YIELD 0
#endif

#endif /* MINI_CONFIG_H */
