set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOL_CHAIN_PREFIX arm-none-eabi- CACHE STRING "Cross-compiler executable prefix")

find_program(CMAKE_C_COMPILER   NAMES ${TOOL_CHAIN_PREFIX}gcc     REQUIRED)
find_program(CMAKE_ASM_COMPILER NAMES ${TOOL_CHAIN_PREFIX}gcc     REQUIRED)
find_program(CMAKE_CXX_COMPILER NAMES ${TOOL_CHAIN_PREFIX}g++     REQUIRED)
find_program(CMAKE_OBJCOPY      NAMES ${TOOL_CHAIN_PREFIX}objcopy REQUIRED)


get_filename_component(CMAKE_C_COMPILER   "${CMAKE_C_COMPILER}"   REALPATH)
get_filename_component(CMAKE_ASM_COMPILER "${CMAKE_ASM_COMPILER}" REALPATH)
get_filename_component(CMAKE_CXX_COMPILER "${CMAKE_CXX_COMPILER}" REALPATH)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
