#!/usr/bin/env python3
"""post_build_crc.py — 固件 / 任意二进制 CRC 校验值生成器

构建后自动运行, 读入二进制文件, 计算 CRC32,
输出 C 头文件宏定义, 供 scrubber 做 Flash 位腐烂检测.

用法:
    python post_build_crc.py --input firmware.bin
                             [--output crc_config.h]
                             [--define FIRMWARE_CRC_BASELINE]
                             [--algo crc32]

    # 传统 ESP-IDF 兼容模式 (位置参数):
    python post_build_crc.py firmware.bin system_scrubber_crc_gen.h

输出示例 (system_scrubber_crc_gen.h):
    #ifndef SYSTEM_SCRUBBER_CRC_BASELINE
    #define SYSTEM_SCRUBBER_CRC_BASELINE 0xA1B2C3D4
    #endif
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
import zlib
from pathlib import Path
from typing import Callable, Dict, Optional


ALGOS: Dict[str, Callable[[bytes], int]] = {
    "crc32": zlib.crc32,
}


def _atomic_write(path: Path, content: str) -> None:
    """原子写入：先写临时文件再 mv 替换，防止生成残缺的头文件"""
    tmp: Path = path.with_suffix(".tmp")
    try:
        tmp.write_text(content, encoding="utf-8")
        shutil.move(str(tmp), str(path))
    except Exception:
        if tmp.exists():
            tmp.unlink()
        raise


def _compute_crc(fw_path: Path, algo: str) -> str:
    """读取二进制文件并计算 CRC 摘要"""
    fw_data: bytes = fw_path.read_bytes()
    crc_fn: Callable[[bytes], int] = ALGOS[algo]
    crc: int = crc_fn(fw_data)
    return f"0x{crc:08X}"


def _replace_in_file(
    path: Path, define_name: str, crc_hex: str
) -> Optional[str]:
    """尝试在现有文件中就地替换宏定义值, 返回实际命中的宏名或 None"""
    content: str = path.read_text(encoding="utf-8")

    # 优先匹配用户指定的宏名
    pattern: str = rf'(#define\s+{re.escape(define_name)}\s+)0x[0-9A-Fa-f]+'
    new_content: str
    count: int
    new_content, count = re.subn(pattern, rf'\g<1>{crc_hex}', content)

    if count > 0:
        _atomic_write(path, new_content)
        return define_name

    # 自动检测文件中已有的 CRC 宏
    m: Optional[re.Match[str]] = re.search(
        r'#define\s+(\w+_CRC_?BASELINE)\s+0x[0-9A-Fa-f]+', content
    )
    if m:
        detected: str = m.group(1)
        pattern = rf'(#define\s+{re.escape(detected)}\s+)0x[0-9A-Fa-f]+'
        new_content, count = re.subn(pattern, rf'\g<1>{crc_hex}', content)
        if count > 0:
            _atomic_write(path, new_content)
            return detected

    return None


def _write_new_header(path: Path, define_name: str, crc_hex: str, fw_path: Path, algo: str) -> None:
    """写全新的 CRC 头文件"""
    lines: str = (
        f"/* Generated by post_build_crc.py — {algo} of {fw_path} */\n"
        f"#ifndef {define_name}\n"
        f"#define {define_name} {crc_hex}\n"
        f"#endif /* {define_name} */\n"
    )
    _atomic_write(path, lines)
    print(
        f"CRC header written: {path} : {define_name} = {crc_hex}"
        f" ({fw_path.stat().st_size} bytes)"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Binary CRC checksum generator")
    parser.add_argument("--input", "-i", type=Path, help="Input binary file")
    parser.add_argument("--output", "-o", type=Path, help="Output C header file (omit for stdout)")
    parser.add_argument(
        "--define", "-d", default="SYSTEM_SCRUBBER_CRC_BASELINE",
        help="C macro name (default: SYSTEM_SCRUBBER_CRC_BASELINE)",
    )
    parser.add_argument(
        "--algo", default="crc32", choices=list(ALGOS),
        help="Hash algorithm (default: crc32)",
    )
    # 位置参数: 兼容旧版 ESP-IDF 用法
    parser.add_argument("pos_input", nargs="?", type=Path, help=argparse.SUPPRESS)
    parser.add_argument("pos_output", nargs="?", type=Path, help=argparse.SUPPRESS)

    args = parser.parse_args()

    fw_path: Optional[Path] = args.input or args.pos_input
    out_path: Optional[Path] = args.output or args.pos_output
    define_name: str = args.define
    algo: str = args.algo

    if fw_path is None:
        print(
            "Usage: python post_build_crc.py --input <binary> [--output <header>]",
            file=sys.stderr,
        )
        sys.exit(1)

    if not fw_path.is_file():
        print(f"ERROR: input not found: {fw_path}", file=sys.stderr)
        sys.exit(1)

    crc_hex: str = _compute_crc(fw_path, algo)

    if out_path is None:
        # 标准输出
        print(
            f"#ifndef {define_name}\n"
            f"#define {define_name} {crc_hex}\n"
            f"#endif /* {define_name} */",
            end="",
        )
        return

    # 尝试就地替换已有宏
    replaced: Optional[str] = _replace_in_file(out_path, define_name, crc_hex)
    if replaced is not None:
        print(
            f"CRC updated in {out_path}: {replaced} = {crc_hex}"
            f" ({fw_path.stat().st_size} bytes)"
        )
        return

    # 不存在 → 写全新头文件
    _write_new_header(out_path, define_name, crc_hex, fw_path, algo)


if __name__ == "__main__":
    main()
