#!/usr/bin/env python3
"""Kconfig → config.h 工业级安全生成器

用法:
    python genconfig.py <kconfig_path> <output_dir> [--config <path>]
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import List

# kconfiglib ships as a single module (pip); namespace packages expose symbols in .core
# ESP-IDF v6.x 使用 esp_kconfiglib 分支, kconfiglib 仅 re-export Kconfig 但不含 BOOL/HEX/INT/STRING 常量
try:
    from kconfiglib import Kconfig, BOOL, HEX, INT, STRING
except ImportError:
    try:
        from kconfiglib.core import Kconfig, BOOL, HEX, INT, STRING
    except ImportError:
        from esp_kconfiglib.core import Kconfig, BOOL, HEX, INT, STRING
try:
    from kconfiglib import TRISTATE
    _BOOL_TYPES = (BOOL, TRISTATE)
except ImportError:
    try:
        from kconfiglib.core import TRISTATE
        _BOOL_TYPES = (BOOL, TRISTATE)
    except ImportError:
        try:
            from esp_kconfiglib.core import TRISTATE
            _BOOL_TYPES = (BOOL, TRISTATE)
        except ImportError:
            _BOOL_TYPES = (BOOL,)


def _atomic_write(path: Path, content: str) -> None:
    """原子写入：先写临时文件再 mv 替换，防止生成残缺的 .h"""
    tmp: Path = path.with_suffix(".tmp")
    try:
        tmp.write_text(content, encoding="utf-8")
        shutil.move(str(tmp), str(path))
    except Exception:
        if tmp.exists():
            tmp.unlink()
        raise


def _build_config_h(kconf: Kconfig) -> str:
    lines: List[str] = [
        "/* SPDX-License-Identifier: Apache-2.0 */",
        "/* Generated by Kconfig — DO NOT EDIT MANUALLY */",
        "#ifndef KCONFIG_CONFIG_H",
        "#define KCONFIG_CONFIG_H",
        "",
    ]

    for sym in kconf.unique_defined_syms:
        if sym.config_string is None or not sym.nodes:
            continue
        name: str = f"CONFIG_{sym.name}"

        if sym.type in _BOOL_TYPES:
            if sym.str_value in ("y", "m"):
                lines.append(f"#define {name} 1")

        elif sym.type in (INT, HEX):
            if sym.str_value != "":
                lines.append(f"#define {name} {sym.str_value}")

        elif sym.type == STRING:
            if sym.str_value:
                raw: str = sym.str_value.strip('"')
                lines.append(f'#define {name} "{raw}"')

    lines.extend(("", "#endif /* KCONFIG_CONFIG_H */", ""))
    return "\n".join(lines)


def _needs_update(path: Path, content: str) -> bool:
    """内容一致时不触碰磁盘，保护 Makefile 时间戳"""
    if not path.exists():
        return True
    return path.read_text(encoding="utf-8") != content


def _sync_dotconfig(kconfig_dir: Path, config_file: Path) -> None:
    """将 .config 同步回 Kconfig 源目录"""
    dst: Path = kconfig_dir / ".config"
    if config_file.resolve() == dst.resolve():
        return
    if config_file.exists():
        shutil.copy(str(config_file), str(dst))


def main() -> None:
    parser = argparse.ArgumentParser(description="Kconfig 工业级代码生成器")
    parser.add_argument("kconfig_path", type=Path, help="Kconfig 文件路径")
    parser.add_argument("output_dir", type=Path, help="config.h 存放目录")
    parser.add_argument("--config", type=Path, default=None, help=".config 文件路径")
    args = parser.parse_args()

    kconfig_path: Path = args.kconfig_path
    output_dir: Path = args.output_dir
    config_file: Path = (
        args.config if args.config is not None else output_dir / ".config"
    )

    if not kconfig_path.is_file():
        sys.exit(f"FATAL: Kconfig 文件不存在 -> {kconfig_path.resolve()}")

    output_dir.mkdir(parents=True, exist_ok=True)

    kconf: Kconfig = Kconfig(str(kconfig_path), warn=False)

    if config_file.exists():
        kconf.load_config(str(config_file))
    else:
        kconf.write_config(str(config_file))

    output_file: Path = output_dir / "config.h"
    new_content: str = _build_config_h(kconf)

    if _needs_update(output_file, new_content):
        _atomic_write(output_file, new_content)
        print(f"[genconfig] Update: {output_file}")
    else:
        print(f"[genconfig] Keep: {output_file} (No changes detected)")

    _sync_dotconfig(kconfig_path.parent, config_file)


if __name__ == "__main__":
    main()
