#!/usr/bin/env python3
"""Kconfig → config.h 工业级安全生成器

用法:
    python genconfig.py <kconfig_path> <output_dir> [config_file]
"""

import sys
import os
import shutil
from kconfiglib import Kconfig, BOOL, TRISTATE, STRING, INT, HEX


def main():
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    kconfig_path = sys.argv[1]
    output_dir = sys.argv[2]
    config_file = sys.argv[3] if len(sys.argv) > 3 else os.path.join(output_dir, ".config")
    output_file = os.path.join(output_dir, "config.h")

    os.makedirs(output_dir, exist_ok=True)

    kconf = Kconfig(kconfig_path, warn=False)

    if os.path.exists(config_file):
        kconf.load_config(config_file)
    else:
        kconf.write_config(config_file)

    lines = [
        "/* SPDX-License-Identifier: MIT */",
        "/* Generated by Kconfig — DO NOT EDIT MANUALLY */",
        "#ifndef KCONFIG_CONFIG_H",
        "#define KCONFIG_CONFIG_H\n"
    ]

    for sym in kconf.unique_defined_syms:
        if sym.config_string is not None and sym.nodes:
            name = f"CONFIG_{sym.name}"

            if sym.type in (BOOL, TRISTATE):
                if sym.str_value in ("y", "m"):
                    lines.append(f"#define {name} 1")

            elif sym.type in (INT, HEX):
                if sym.str_value != "":
                    lines.append(f"#define {name} {sym.str_value}")

            elif sym.type == STRING:
                if sym.str_value:
                    raw_val = sym.str_value.strip('"')
                    lines.append(f'#define {name} "{raw_val}"')

    lines.append("\n#endif /* KCONFIG_CONFIG_H */\n")
    new_content = "\n".join(lines)

    should_write = True
    if os.path.exists(output_file):
        with open(output_file, "r", encoding="utf-8") as f:
            if f.read() == new_content:
                should_write = False

    if should_write:
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(new_content)
        print(f"[genconfig] Update: {output_file}")
    else:
        print(f"[genconfig] Keep: {output_file} (No changes detected)")

    src_config = os.path.join(os.path.dirname(kconfig_path), ".config")
    if os.path.abspath(config_file) != os.path.abspath(src_config):
        try:
            same = os.path.samefile(config_file, src_config)
        except FileNotFoundError:
            same = False
        except AttributeError:
            same = os.path.abspath(config_file) == os.path.abspath(src_config)
        if not same:
            shutil.copy(config_file, src_config)


if __name__ == "__main__":
    main()
