#!/usr/bin/env python3
"""
post_build_crc.py  — 固件 / 任意二进制 CRC 校验值生成器

构建后自动运行, 读入二进制文件, 计算 CRC32,
输出 C 头文件宏定义, 供 scrubber 做 Flash 位腐烂检测.

用法:
    python post_build_crc.py --input firmware.bin
                             [--output crc_config.h]
                             [--define FIRMWARE_CRC_BASELINE]
                             [--algo crc32]

    # 传统 ESP-IDF 兼容模式 (位置参数):
    python post_build_crc.py firmware.bin board_config.h

输出示例 (crc_config.h):
    #ifndef FIRMWARE_CRC_BASELINE
    #define FIRMWARE_CRC_BASELINE 0xA1B2C3D4
    #endif
"""

import sys
import os
import argparse
import zlib
import re


ALGOS = {
    "crc32": zlib.crc32,
}


def main():
    parser = argparse.ArgumentParser(description="Binary CRC checksum generator")
    parser.add_argument("--input", "-i", help="Input binary file")
    parser.add_argument("--output", "-o", help="Output C header file (omit for stdout)")
    parser.add_argument("--define", "-d", default="FIRMWARE_CRC_BASELINE",
                        help="C macro name (default: FIRMWARE_CRC_BASELINE)")
    parser.add_argument("--algo", default="crc32", choices=list(ALGOS),
                        help="Hash algorithm (default: crc32)")
    # 位置参数: 兼容旧版 ESP-IDF 用法: <firmware.bin> <board_config_path>
    parser.add_argument("pos_input", nargs="?", help=argparse.SUPPRESS)
    parser.add_argument("pos_output", nargs="?", help=argparse.SUPPRESS)

    args = parser.parse_args()

    # 兼容旧版: 位置参数转命名参数
    fw_path = args.input or args.pos_input
    out_path = args.output or args.pos_output

    if not fw_path:
        print("Usage: python post_build_crc.py --input <binary> [--output <header>]", file=sys.stderr)
        sys.exit(1)

    if not os.path.exists(fw_path):
        print(f"ERROR: input not found: {fw_path}", file=sys.stderr)
        sys.exit(1)

    with open(fw_path, "rb") as f:
        fw_data = f.read()

    crc_fn = ALGOS[args.algo]
    crc = crc_fn(fw_data)
    crc_hex = f"0x{crc:08X}"

    define_name = args.define
    header = (
        f"#ifndef {define_name}\n"
        f"#define {define_name} {crc_hex}\n"
        f"#endif /* {define_name} */\n"
    )

    if out_path:
        # 尝试就地替换已存在的宏定义 (兼容旧版 board_config.h 风格)
        if os.path.exists(out_path):
            with open(out_path, "r") as f:
                content = f.read()

            # 优先匹配用户指定的 define_name, 否则自动检测文件中已存在的宏
            pattern = rf'(#define\s+{re.escape(define_name)}\s+)0x[0-9A-Fa-f]+'
            new_content, count = re.subn(pattern, rf'\g<1>{crc_hex}', content)

            if count == 0:
                # 自动检测文件中是否已有其他 CRC 宏
                m = re.search(r'#define\s+(\w+_CRC_?BASELINE)\s+0x[0-9A-Fa-f]+', content)
                if m:
                    define_name = m.group(1)
                    pattern = rf'(#define\s+{re.escape(define_name)}\s+)0x[0-9A-Fa-f]+'
                    new_content, count = re.subn(pattern, rf'\g<1>{crc_hex}', content)

            if count > 0:
                with open(out_path, "w") as f:
                    f.write(new_content)
                print(f"CRC updated in {out_path}: {define_name} = {crc_hex} ({len(fw_data)} bytes)")
                return

        # 宏不存在 → 写完整头文件
        with open(out_path, "w") as f:
            f.write(f"/* Generated by post_build_crc.py — {args.algo} of {fw_path} */\n")
            f.write(header)
        print(f"CRC header written: {out_path} : {define_name} = {crc_hex} ({len(fw_data)} bytes)")
    else:
        print(header, end="")


if __name__ == "__main__":
    main()
